name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: nn_lib tests forward
        run: python -m unittest nn_lib/tests/test_tensor_forward.py
      - name: nn_lib tests backward
        run: python -m unittest nn_lib/tests/test_tensor_backward.py
      - name: nn_lib tests optim
        run: python -m unittest nn_lib/tests/test_optim.py
      - name: nn_lib tests modules
        run: python -m unittest nn_lib/tests/test_modules.py